services:
  db:
    image: postgres
    volumes:
      - tass_db_data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - 127.0.0.1:5434:5432
  web:
    build: ./tass_project
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./tass_project:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - env.dev

volumes:
  tass_db_data:
