# Generated by Django 3.2.16 on 2023-01-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20230106_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
