# Generated by Django 3.2.16 on 2023-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20230112_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='airport',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='airport',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
