# Generated by Django 3.2.16 on 2023-01-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_city_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_ascii',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.CharField(max_length=80),
        ),
    ]
