# Generated by Django 3.2.16 on 2023-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_auto_20230112_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
